# Generated by Django 5.1 on 2026-04-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Evento_nome", models.CharField(max_length=50)),
                ("Evento_tipo", models.CharField(max_length=50)),
                ("Evento_materia", models.CharField(max_length=50)),
                ("Evento_entrega", models.DateField()),
                ("Evento_repetir", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Ususario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Usuario_nome",
                    models.CharField(max_length=50, verbose_name="Seu 🫵 nome"),
                ),
                (
                    "Usuario_email",
                    models.EmailField(max_length=254, verbose_name="Seu E-mail"),
                ),
                (
                    "Usuario_senha",
                    models.CharField(max_length=30, verbose_name="Seu nome"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Anexo_nome",
                    models.CharField(max_length=50, verbose_name="Nome do Anexo"),
                ),
                (
                    "Anexo_arquivo",
                    models.FileField(upload_to="", verbose_name="Arquivo"),
                ),
                (
                    "Anexo_tamanho",
                    models.PositiveIntegerField(verbose_name="Tamanho do Arquivo"),
                ),
                (
                    "Anexo_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_legal_e_bacana.evento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lembrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Lembrete_nome",
                    models.CharField(max_length=50, verbose_name="Nome do lembrete"),
                ),
                ("Lembrete_date", models.DateField(verbose_name="Data do lembrete")),
                (
                    "Lembrete_desc",
                    models.TextField(
                        blank=True,
                        default="Eu sou uma descrição padrão. Ha",
                        max_length=250,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "Lembrete_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_legal_e_bacana.evento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subtarefa_nome", models.CharField(max_length=50)),
                ("Subtarefa_concluida", models.BooleanField()),
                (
                    "Subtarefa_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_legal_e_bacana.evento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="Evento_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="site_legal_e_bacana.ususario",
            ),
        ),
    ]
