# Generated by Django 5.1 on 2026-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_legal_e_bacana", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ususario",
            new_name="Usuario",
        ),
    ]
