# Generated by Django 5.1 on 2026-04-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_legal_e_bacana", "0003_alter_evento_evento_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="Evento_usuario",
        ),
    ]
