# Generated by Django 6.0.4 on 2026-05-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_legal_e_bacana', '0004_remove_evento_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='Evento_descricao',
            field=models.TextField(default='naoexistia', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
