# Generated by Django 5.1 on 2026-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_legal_e_bacana", "0005_evento_evento_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="Evento_anexos",
            field=models.FileField(
                default="legal.txt", upload_to="documentos/", verbose_name="Anexos"
            ),
            preserve_default=False,
        ),
    ]
