# Generated by Django 6.0.4 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_legal_e_bacana', '0006_evento_evento_anexos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participante_nome', models.CharField(max_length=50, verbose_name='Nome dele')),
                ('Participante_email', models.EmailField(max_length=254, verbose_name='E-mail dele')),
                ('Participante_senha', models.CharField(max_length=30, verbose_name='Senha dele')),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Evento_anexos',
        ),
    ]
