# Generated by Django 5.1 on 2026-06-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_legal_e_bacana", "0007_participante_remove_evento_evento_anexos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="Anexo_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evento",
            name="Evento_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lembrete",
            name="Lembrete_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subtarefa",
            name="Subtarefa_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="anexo",
            name="Anexo_arquivo",
            field=models.CharField(verbose_name="Arquivo"),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="Anexo_evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="site_legal_e_bacana.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="lembrete",
            name="Lembrete_evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="site_legal_e_bacana.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="subtarefa",
            name="Subtarefa_evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="site_legal_e_bacana.evento",
                verbose_name="Evento",
            ),
        ),
    ]
